- name: setup db servers
  hosts: db_servers
  remote_user: "{{ remote_user }}"

  tasks:
  - name: install postgres servers
    ansible.builtin.apt:
      name: postgresql
      state: present
      update_cache: yes
    become: yes

  - name: install acl
    ansible.builtin.apt:
      name: acl
      state: present
      update_cache: yes
    become: yes 

  - name: Install psycopg2
    ansible.builtin.apt:
      name: python3-psycopg2
      state: present
      update_cache: yes
    become: yes

  - name: ensure postgresql is running
    ansible.builtin.service:
      name: postgresql
      state: started
      enabled: yes

  - name: create postgresql mealplanner user
    community.postgresql.postgresql_user:
      name: "{{ database_user }}"
      password: mealplanner
      state: present
    become: yes
    become_user: postgres
    become_method: sudo

  - name: create mealplanner database
    community.postgresql.postgresql_db:
      name: "{{ database_name }}"
      owner: "{{ database_user }}"
      state: present
    become: yes
    become_user: postgres
    become_method: sudo

