- name: setup db servers
  hosts: db_servers
  remote_user: ubuntu 

  tasks:
  - name: install postgres servers
    ansible.builtin.apt:
      name: postgresql
      state: present
      update_cache: yes
    become: yes

  - name: install acl
    ansible.builtin.apt:
      name: acl
      state: present
      update_cache: yes
    become: yes 

  - name: Install psycopg2
    ansible.builtin.apt:
      name: python3-psycopg2
      state: present
      update_cache: yes
    become: yes

  - name: ensure postgresql is running
    ansible.builtin.service:
      name: postgresql
      state: started
      enabled: yes

  - name: create postgresql mealplanner user
    community.postgresql.postgresql_user:
      name: mealplanner
      password: mealplanner
      state: present
    become: yes
    become_user: postgres

  - name: create mealplanner database
    community.postgresql.postgresql_db:
      name: mealplanner
      owner: mealplanner
      state: present
    become: yes

