- name: Set up web servers
  hosts: web_servers
  remote_user: "{{ remote_user }}"
  become: yes

  tasks:
  - name: Read current release version on server
    set_fact:
      app_release: "{{ ansible_env.APP_RELEASE | default('UNSET') }}"
      

  - name: Check current release vs server variable
    set_fact:
      app_release_matches: "{{ app_release == mealplanner_release }}"

  - name: Create web application directory
    ansible.builtin.file:
      path: "{{ app_path }}"
      state: directory
      owner: "{{ remote_user }}"
      group: "{{ remote_user }}"
      mode: "0755"

  - name: Create environment variable file
    ansible.builtin.copy:
      dest: "{{ app_path }}/.env"
      content: |
        ASPNETCORE_ENVIRONMENT="{{ app_environment }}"        
      owner: "{{ remote_user }}"
      group: "{{ remote_user }}"
      mode: "0644"

  - name: Copy web application files
    ansible.builtin.copy:
      src: "/home/ubuntu/actions-runner/_work/MealPlannerApi/MealPlannerApi/publish/release-{{ mealplanner_release }}/"
      dest: "{{ app_path }}"
      owner: "{{ remote_user }}"
      group: "{{ remote_user }}"
      mode: "0755"
      remote_src: false
    when: not app_release_matches
    notify:
      - restart mealplannerapi
      - set app_release
    

  - name: Ensure MealPlannerApi binary is executable
    ansible.builtin.file:
      path: "{{ app_path }}/MealPlannerApi"
      mode: "0755"
      owner: "{{ remote_user }}"
      group: "{{ remote_user }}"
      state: file
    notify:
      - restart mealplannerapi

  - name: Create systemd service file
    ansible.builtin.copy:
      dest: /etc/systemd/system/mealplannerapi.service
      content: |
        [Unit]
        Description=.NET Core Meal Planner API Service
        After=network.target

        [Service]
        User=ubuntu
        EnvironmentFile={{ app_path }}/.env
        WorkingDirectory={{ app_path }}
        ExecStart={{ app_path }}/MealPlannerApi
        Restart=always
        RestartSec=10
        KillSignal=SIGINT
        SyslogIdentifier=mealplannerapi

        [Install]
        WantedBy=multi-user.target
      mode: "0644"
    notify:
      - reload systemd
      - restart mealplannerapi

  - name: Enable and start MealPlanner API service
    ansible.builtin.systemd:
      name: mealplannerapi
      enabled: yes
      state: started

  handlers:
  - name: reload systemd
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: restart mealplannerapi
    ansible.builtin.systemd:
      name: mealplannerapi
      state: restarted
  
  - name: set app_release environment variable
    ansible.builtin.lineinfile:
      path: /etc/environment
      regexp: '^APP_RELEASE='
      line: "APP_RELEASE={{ mealplanner_release }}"
      create: yes
  

