- name: setup db servers
  hosts: db_servers
  remote_user: ubuntu
  become: yes 

  tasks:
  - name: install mysql servers
    ansible.builtin.apt:
      name: mysql-server
      state: present
      update_cache: yes 

  - name: Install PyMySQL
    ansible.builtin.apt:
      name: python3-pymysql
      state: present
      update_cache: yes

  - name: ensure mysql is running
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes
  
  - name: create mysql mealplanner user 
    community.mysql.mysql_user:
      name: mealplanner
      password: mealplanner
      host: localhost
      priv: '*.*:ALL'
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
    become: yes

  - name: Test MySQL connection with mealplanner user
    community.mysql.mysql_info:
      login_user: mealplanner
      login_password: mealplanner
      login_host: localhost
    