- name: setup db servers
  hosts: db_servers
  remote_user: "{{ remote_user }}"
  become: yes

  tasks:
  - name: install postgres servers
    ansible.builtin.apt:
      name: postgresql
      state: present
      update_cache: yes

  - name: install required packages
    ansible.builtin.apt:
      name:
        - acl
        - python3-psycopg2
      state: present
      update_cache: yes

  - name: ensure postgresql is running
    ansible.builtin.service:
      name: postgresql
      state: started
      enabled: yes

  - name: create postgresql mealplanner user
    community.postgresql.postgresql_user:
      name: "{{ database_user }}"
      password: mealplanner
      state: present
    become: yes
    become_user: postgres
    become_method: sudo

  - name: create mealplanner database
    community.postgresql.postgresql_db:
      name: "{{ database_name }}"
      owner: "{{ database_user }}"
      state: present
    become: yes
    become_user: postgres
    become_method: sudo

  - name: add mealplanner user to pg_hba.conf
    community.postgresql.postgresql_pg_hba:
      dest: /etc/postgresql/16/main/pg_hba.conf
      contype: host
      users: "{{ database_user }}"
      source: "{{ local_subnet }}"
      databases: "{{ database_name }}"
      method: md5
    notify:
      - restart postgresql

  - name: change listening address in postgresql.conf
    community.postgresql.postresql_set:
      name: listen_addresses
      value: '*'
    notify:
      - restart postgresql

  handlers:
  - name: restart postgresql
    ansible.builtin.service:
      name: postgresql
      state: restarted

