apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mealplanner
spec:
  type: ClusterIP
  selector:
    app: mealplanner-frontend
  ports:
    - port: 80
      targetPort: 8090