apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-api-deployment
  namespace: mealplanner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mealplanner-api
  template:
    metadata:
      labels:
        app: mealplanner-api
    spec:
      containers:
      - name: mealplanner-api
        image: richn987/mealplannerapi:master
        ports:
        - containerPort: 8080