apiVersion: v1
kind: Secret
metadata:
  name: mp-api-secret
  namespace: mealplanner
type: Opaque
stringData:
  connectionstrings__defaultconnection: "Host=192.168.178.73;Database=mealplanner;Username=mealplanner;Password=mealplanner"
